# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tf_ios_makefile_example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tf_ios_makefile_example
  pod 'NYTPhotoViewer', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'

end
